name: quomia
description: "A new Flutter project."
publish_to: "none"
version: 0.0.5

environment:
  sdk: ^3.5.2

dependencies:
  carousel_slider: ^5.0.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  lottie: ^3.1.2
  percent_indicator: ^4.2.3
  pin_code_fields: ^8.0.1
  simple_gradient_text: ^1.3.0
  video_player: ^2.9.2
  intl: ^0.18.0
  file_picker: ^5.2.5
  firebase_storage: ^12.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/videos/sample_video.mp4
    - assets/animations/intro.json
    - assets/animations/hourglass.json
    - assets/images/quomia_logo.png
    - assets/images/img_1.jpeg
    - assets/images/img_2.jpeg
    - assets/images/img_3.jpeg
